In [3]:
import numpy as np

## numpy array

In [6]:
benimList=[20,30,40]

In [7]:
np.array(benimList)

array([20, 30, 40])

In [8]:
matrixListesi=[[10,20,30],[20,30,50],[50,60,70]]

In [9]:
matrixListesi[1][0]

20

In [10]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 50],
       [50, 60, 70]])

## methods

In [11]:
## arange

In [12]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [17]:
## zeros

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(13)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
##linspace

In [24]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [27]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [28]:
##eye

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [30]:
## random

In [36]:
np.random.randn(4)

array([-1.19827232,  0.45717818, -1.89867869,  2.17062001])

In [37]:
np.random.randn(3,3)

array([[ 0.51609215, -1.22629977, -0.62341906],
       [-0.13909799,  0.19843912,  0.32734867],
       [-0.24810775,  0.42033134, -0.91017962]])

In [44]:
## 100 donmez
np.random.randint(1,100)

75

In [46]:
np.random.randint(1,100,10)

array([89, 21, 91, 61, 58, 25, 96, 20,  5, 72])

In [47]:
x=np.random.randint(1,100)

In [48]:
x

78

In [49]:
benimDizi=np.arange(30)

In [50]:
benimDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [52]:
benimRandDizi=np.random.randint(0,100,20)

In [53]:
benimRandDizi

array([11, 67, 67, 79, 45, 68, 16, 80, 34, 96, 68, 66, 65,  1, 44, 27, 99,
       42, 92, 78])

In [55]:
##numpy dizi methodları

In [56]:
benimDizi.reshape(5,5)

ValueError: cannot reshape array of size 30 into shape (5,5)

In [66]:
## benimDizi değişmez yeni bir dizi döndürür
benimDizi.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [58]:
benimDizi.max()

29

In [59]:
benimRandDizi.min()

1

In [63]:
## en yuksek degerin indexi
benimRandDizi.argmax()

16

In [65]:
benimDizi.shape

(30,)

In [67]:
benimNpDizi=benimDizi.reshape(6,5)

In [68]:
benimNpDizi.shape

(6, 5)

In [69]:
benimNpDizi

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [3]:
benimDizim=np.arange(0,15)

In [4]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
benimDizim[5]

5

In [7]:
benimDizim[3:7]

array([3, 4, 5, 6])

In [8]:
benimDizim[3:8]=-8

In [9]:
benimDizim

array([ 0,  1,  2, -8, -8, -8, -8, -8,  8,  9, 10, 11, 12, 13, 14])

In [10]:
baskaDizi=np.arange(0,24)

In [15]:

slicingDizi=baskaDizi[4:11]

In [16]:
slicingDizi

array([ 4,  5,  6,  7,  8,  9, 10])

In [17]:
slicingDizi[:]=700

In [18]:
slicingDizi

array([700, 700, 700, 700, 700, 700, 700])

In [19]:
##aldıgın parça ana dizide de değişiyor
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700, 700, 700,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [20]:
ornekDizi=np.arange(0,24)

In [21]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
ornekDiziKopyasi=ornekDizi.copy()

In [23]:
ornekDiziSlicing=ornekDiziKopyasi[2:8]

In [24]:
ornekDiziSlicing[:]=199

In [25]:
ornekDiziSlicing

array([199, 199, 199, 199, 199, 199])

In [26]:
ornekDiziKopyasi

array([  0,   1, 199, 199, 199, 199, 199, 199,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [27]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
###matrix####

In [29]:
matrixListesi=[[10,20,30],[20,30,50],[50,60,70]]

In [30]:
benimMatrix=np.array(matrixListesi)

In [31]:
benimMatrix

array([[10, 20, 30],
       [20, 30, 50],
       [50, 60, 70]])

In [32]:
benimMatrix[1]

array([20, 30, 50])

In [34]:
benimMatrix[2,2]

70

In [35]:
benimMatrix[1][1]

30

In [36]:
benimMatrix[1:,2]

array([50, 70])

In [37]:
benimMatrix[2:,2:]

array([[70]])

In [38]:
yeniListe=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]

In [39]:
yeniM=np.array(yeniListe)

In [40]:
yeniM[[0,3]]

array([[ 1,  2,  3,  4,  5],
       [16, 17, 18, 19, 20]])

In [41]:
yeniM

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [1]:
##operasyonlar

In [5]:
yeniBirDizi=np.random.randint(1,100,25)

In [6]:
yeniBirDizi

array([85, 20, 19, 20, 64, 66, 59, 41, 26, 76, 86, 59, 73, 57, 30, 44, 38,
       92, 74, 60, 38, 65, 33, 47, 68])

In [7]:
yeniBirDizi>20

array([ True, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [11]:
sonucDizisi=yeniBirDizi>80

In [12]:
sonucDizisi

array([ True, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False])

In [13]:
yeniBirDizi[sonucDizisi]

array([85, 86, 92])

In [14]:
yeniBirDizi[yeniBirDizi>30]

array([85, 64, 66, 59, 41, 76, 86, 59, 73, 57, 44, 38, 92, 74, 60, 38, 65,
       33, 47, 68])

In [16]:
sonDizi=np.arange(0,24)

In [18]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [19]:
sonDizi*sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [20]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [21]:
np.max(sonDizi)

23